apiVersion: apps/v1
kind: Deployment
metadata:
  name: courseproj1-frontend
  labels:
    app: courseproj1-frontend
spec:
  selector:
    matchLabels:
      app: courseproj1-frontend
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: courseproj1-frontend
    spec:
      containers:
        - image: nqmaigre/courseproj1-frontend:latest
          imagePullPolicy: Always
          name: courseproj1-frontend
          ports:
            - containerPort: 80
